#!/usr/bin/env bash
set -euo pipefail

SUBSCRIPTION_NAME="UC Davis CAES Test"
SUBSCRIPTION_ID="105dede4-4731-492e-8c28-5121226319b0"

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
DEPLOY_SCRIPT="$SCRIPT_DIR/deploy.sh"

RESOURCE_GROUP="${RESOURCE_GROUP:-CruSibyl-Test}"
LOCATION="${LOCATION:-westus2}"
APP_NAME="${APP_NAME:-crusibyl}"
ENVIRONMENT="${ENVIRONMENT:-test}"
DEPLOYMENT_NAME="${DEPLOYMENT_NAME:-${APP_NAME}-${ENVIRONMENT}}"
SQL_ADMIN_LOGIN="${SQL_ADMIN_LOGIN:-}"
DEPLOY_MONITORING="${DEPLOY_MONITORING:-true}"

env \
  SUBSCRIPTION_NAME="$SUBSCRIPTION_NAME" \
  SUBSCRIPTION_ID="$SUBSCRIPTION_ID" \
  RESOURCE_GROUP="$RESOURCE_GROUP" \
  LOCATION="$LOCATION" \
  APP_NAME="$APP_NAME" \
  ENVIRONMENT="$ENVIRONMENT" \
  DEPLOYMENT_NAME="$DEPLOYMENT_NAME" \
  SQL_ADMIN_LOGIN="$SQL_ADMIN_LOGIN" \
  SQL_ADMIN_PASSWORD="${SQL_ADMIN_PASSWORD:-}" \
  DEPLOY_MONITORING="$DEPLOY_MONITORING" \
  APP_SERVICE_PLAN_SKU="${APP_SERVICE_PLAN_SKU:-B1}" \
  APP_SERVICE_PLAN_TIER="${APP_SERVICE_PLAN_TIER:-Basic}" \
  APP_SERVICE_PLAN_CAPACITY="${APP_SERVICE_PLAN_CAPACITY:-1}" \
  AZURE_SYNC_SUBSCRIPTION_ROLE="${AZURE_SYNC_SUBSCRIPTION_ROLE:-}" \
  "$DEPLOY_SCRIPT"
